name: Lint and check code formatting

on:
  push:
    branches:
      - main
      - make-money-v3
  pull_request:
    branches:
      - main
      - make-money-v3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Setup environment
        run: |
          echo "JESTOR_TOKEN=abc123" > .env
          echo "JESTOR_ORG=sauron" >> .env

      - name: Lint
        run: pnpm lint
